# Generated by Django 5.2.10 on 2026-02-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('beds', models.IntegerField()),
                ('baths', models.FloatField()),
                ('sqft', models.IntegerField()),
                ('built', models.IntegerField()),
                ('description', models.TextField()),
                ('images', models.JSONField()),
                ('agent', models.JSONField()),
                ('neighborhood', models.CharField(max_length=255)),
                ('features', models.JSONField()),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
