# Generated by Django 5.2.10 on 2026-02-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='original_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
