# Generated by Django 5.1.6 on 2026-02-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_original_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='panorama_images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
