# Generated by Django 5.1.6 on 2026-02-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='has_online_lock',
            field=models.BooleanField(default=False),
        ),
    ]
